### ISSUE TITLE
Create Gene missing updated style

### ISSUE THREAD

**Issue by torridgristle** [jannik323/artbreederplus#1]
On the Create Gene page there's several elements that aren't updated to fit AB+'s dark style. Using Firefox 85.0.2 (64-bit), AB+ 9.2, no additional scripts or addons interacting with the page apart from uBlock Origin.

![Create Gene](https://user-images.githubusercontent.com/23273466/156776104-d18162f7-ab63-49bd-afd2-5c998379c1fa.png)

**Comment by jannik323** [comment]
Ah, i don't have Artbreeder Pro right now . Is it possible for you to [right click -> inspect]  the elements/containers, that are unaffected by ab+ and send me a screenshot of the inspect page? (with the classes in the screenshot) discord or here . Make sure there arent any credentials or something in the picture (tho the stripe iframe should be all the way at the bottom)

**Comment by jannik323** [comment]
Fixed in the the newest version 9.3 👍
