### ISSUE TITLE
Enhancement: Create Gene missing the "Negative Images" section

### ISSUE THREAD

**Issue by torridgristle** [jannik323/artbreederplus#2]
In Create Gene that's a hidden div with the id `negative-images`. Simply removing `class="hidden"` will make it function properly. Given the scope of AB+ I reckon this feature should enabled.

It looks a bit different from the `positive-images` div so it may be worth replacing parts of the `negative-images` div to make it look the same as the `positive-images` for the sake of aesthetics. I'd done this in the past, just replacing and moving some parts around.

**Comment by jannik323** [comment]
Added a option in the settings to enable / unhide the hidden negative images. Its on by default
